version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
    timezone: Europe/Madrid
  ignore:
  - dependency-name: eslint
    versions:
    - ">= 7.a, < 8"
  - dependency-name: core-js
    versions:
    - 3.10.2
    - 3.9.1
  - dependency-name: sass-loader
    versions:
    - 11.0.1
  - dependency-name: node-sass
    versions:
    - 5.0.0
  - dependency-name: eslint-plugin-vue
    versions:
    - 7.7.0
    - 7.8.0
  - dependency-name: vue-router
    versions:
    - 3.5.1
  - dependency-name: "@vue/cli-plugin-babel"
    versions:
    - 4.5.12
  - dependency-name: "@vue/cli-service"
    versions:
    - 4.5.12
  - dependency-name: elliptic
    versions:
    - 6.5.4
